apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesJson6902:
- path: ingress-host-patch.yaml
  target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: notejam
    namespace: notejam